[package]
name = "fmod"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.59.1"

[dev-dependencies]
serial_test = "0.5.1"
